// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrdemServico.Models;

#nullable disable

namespace OrdemServico.Migrations
{
    [DbContext(typeof(DBSenaiTechContext))]
    [Migration("20250424130339_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OrdemServico.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"), 1L, 1);

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomeCliente");

                    b.HasKey("IdCliente")
                        .HasName("PK__Clientes__885457EE011734EE");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("OrdemServico.Models.Defeito", b =>
                {
                    b.Property<int>("IdDefeito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDefeito");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDefeito"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descricao");

                    b.HasKey("IdDefeito")
                        .HasName("PK__Defeitos__9549F9F7BD729DE1");

                    b.ToTable("Defeitos");
                });

            modelBuilder.Entity("OrdemServico.Models.Equipamento", b =>
                {
                    b.Property<int>("IdEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEquipamento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipamento"), 1L, 1);

                    b.Property<string>("NomeEquipamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomeEquipamento");

                    b.HasKey("IdEquipamento")
                        .HasName("PK__Equipame__75940D34D0CF45D2");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("OrdemServico.Models.OrdensServico", b =>
                {
                    b.Property<int>("IdOrdemServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idOrdemServico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdemServico"), 1L, 1);

                    b.Property<DateTime>("DataOrdemServico")
                        .HasColumnType("date")
                        .HasColumnName("dataOrdemServico");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdDefeito")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipamento")
                        .HasColumnType("int");

                    b.Property<int>("IdTecnico")
                        .HasColumnType("int");

                    b.Property<string>("Servico")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("servico");

                    b.Property<int>("StatusServico")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("statusServico");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valorTotal");

                    b.HasKey("IdOrdemServico")
                        .HasName("PK__OrdensSe__976593105C89ACCE");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdDefeito");

                    b.HasIndex("IdEquipamento");

                    b.HasIndex("IdTecnico");

                    b.ToTable("OrdensServicos");
                });

            modelBuilder.Entity("OrdemServico.Models.Tecnico", b =>
                {
                    b.Property<int>("IdTecnico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTecnico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTecnico"), 1L, 1);

                    b.Property<string>("NomeTecnico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomeTecnico");

                    b.HasKey("IdTecnico")
                        .HasName("PK__Tecnicos__295BEDE46571E492");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("OrdemServico.Models.OrdensServico", b =>
                {
                    b.HasOne("OrdemServico.Models.Cliente", "IdClienteNavigation")
                        .WithMany("OrdensServicos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrdensSer__idCli__4222D4EF");

                    b.HasOne("OrdemServico.Models.Defeito", "IdDefeitoNavigation")
                        .WithMany("OrdensServicos")
                        .HasForeignKey("IdDefeito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrdensSer__idDef__4316F928");

                    b.HasOne("OrdemServico.Models.Equipamento", "IdEquipamentoNavigation")
                        .WithMany("OrdensServicos")
                        .HasForeignKey("IdEquipamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrdensSer__idEqu__412EB0B6");

                    b.HasOne("OrdemServico.Models.Tecnico", "IdTecnicoNavigation")
                        .WithMany("OrdensServicos")
                        .HasForeignKey("IdTecnico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrdensSer__idTec__440B1D61");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDefeitoNavigation");

                    b.Navigation("IdEquipamentoNavigation");

                    b.Navigation("IdTecnicoNavigation");
                });

            modelBuilder.Entity("OrdemServico.Models.Cliente", b =>
                {
                    b.Navigation("OrdensServicos");
                });

            modelBuilder.Entity("OrdemServico.Models.Defeito", b =>
                {
                    b.Navigation("OrdensServicos");
                });

            modelBuilder.Entity("OrdemServico.Models.Equipamento", b =>
                {
                    b.Navigation("OrdensServicos");
                });

            modelBuilder.Entity("OrdemServico.Models.Tecnico", b =>
                {
                    b.Navigation("OrdensServicos");
                });
#pragma warning restore 612, 618
        }
    }
}
